// Generated by CoffeeScript 1.10.0
(function() {
  jQuery(function() {
    return $('#quest_potterr').change(function() {
      var potterr_id, pwheels_path, pwheels_path_with_params;
      potterr_id = $('#quest_potterr').val();
      pwheels_path = $('#quest_pwheel_id').data('ajax-path');
      pwheels_path_with_params = pwheels_path + "?potterr_id=" + potterr_id;
      if (potterr_id) {
        return $.ajax(pwheels_path_with_params, {
          type: 'GET',
          dataType: 'script'
        });
      }
    });
  });

}).call(this);
